### PR TITLE
fix(services):  Adds temporary try/catch to avoid crashes.

### PR DESCRIPTION
**Pull request by Enuviel**

### CODE REVIEW

**Comment by Enuviel** [comment]
test this please

**Comment by Enuviel** [comment]
We don't need to log something.

**Comment by Enuviel** [comment]
We don't need to log something.

**Comment by alexisoyama** [comment]
Okay, that’s fine but can you tell me more about the fix / what’s going on here?

**Comment by Enuviel** [comment]
test this please

**Comment by sayaansaha** [comment]
test this please

**Pull request closed without merging**
