### PR TITLE
Adding track method with argument parameter.

### PR DESCRIPTION
**Pull request by benmarten**
This is the #68 with added unit test.

### CODE REVIEW

**Comment by benmarten** [comment]
@richardortiz84 We discussed this PR further in the team, and we are hesitant to expose the args parameter completely, as this could lead to confusion among other customers.
I believe what you were looking for could be achieved by using https://github.com/Leanplum/Leanplum-Android-SDK/blob/master/AndroidSDK/src/com/leanplum/Leanplum.java#L1528 ?
I don't think currencyCode is available in iOS but we can add a similar method for iOS....

**Comment by richardortiz84** [comment]
@benmarten Calling another event does not achieve what we are trying to do. We have another event that is being used for track purchases where we send in a currency. The track function not having a currency code is a problem because our application takes in currencies other than USD and we need those converted so that we can properly target our audience.

**Comment by alexisoyama** [comment]
Hi @richardortiz84. I believe what you are looking for is a track method that takes currency code. This is a valid case for non in-app purchase apps. I need to confirm with the team but we will most likely make a new method that will cover this case. If so we will make it. No need to make a PR.

**Comment by benmarten** [comment]
I'm not sure if we made any progress on this request. Let's discuss in todays sprint planning...

**Comment by benmarten** [comment]
We have added a task in our current sprint, to add a new method to support this use case.

**Comment by benmarten** [comment]
Resolved by https://github.com/Leanplum/Leanplum-Android-SDK/pull/77 @richardortiz84

**Pull request closed without merging**
