### PR TITLE
correct pathspec for build.sh

### PR DESCRIPTION
**Pull request by sayaansaha**
Correctly points path to android dir in build.sh

### CODE REVIEW

**Comment by sayaansaha** [comment]
test this please

**Comment by benmarten** [comment]
Hm, not sure if this actually helps. `build.sh` is the standalone build script, means any customer should be able to run the build without lpm, please refer to: https://github.com/Leanplum/Leanplum-Android-SDK/blob/master/README.md#build-the-sdk
Build fails too....

**Comment by Enuviel** [comment]
@sayaansaha  could we close this one?

**Comment by sayaansaha** [comment]
I'm going to test this and update this PR, I still think there is something going on here.

**Comment by Enuviel** [comment]
I'm closing this PR for now, please open a new one, when you have done with testing. Thank you!

**Pull request closed without merging**
