### PR TITLE
Refactor gradle files

### PR DESCRIPTION
**Pull request by acconway**
test this please

### CODE REVIEW

**Comment by acconway** [comment]
test this please

**Comment by Enuviel** [comment]
test this please

**Comment by acconway** [comment]
test this please

**Comment by MaitreyaBuddha** [comment]
test this please

**Comment by acconway** [comment]
The build breaks here on the Test App, because I'm putting a lot of logic in the top build file for the Android SDK project, which is not shared by the test app project.

**Comment by acconway** [comment]
Doing https://github.com/Leanplum/Leanplum-Android-SDK/pull/140 instead

**Pull request closed without merging**
