### PR TITLE
feat(gradle): adding support for android studio 3.0 and gradle 4.1

### PR DESCRIPTION
**Pull request by milos1290**

### CODE REVIEW

**Comment by AlexZvonik** [comment]
I'm not sure but probably this PR will solve my issue:
https://github.com/Leanplum/Leanplum-Android-SDK/issues/113

**Comment by milos1290** [comment]
retest this please

**Comment by milos1290** [comment]
retest this please

**Comment by milos1290** [comment]
test this please

**Comment by milos1290** [comment]
test this please

**Comment by milos1290** [comment]
test this please

**Comment by milos1290** [comment]
test this please

**Comment by milos1290** [comment]
test this please

**Comment by milos1290** [comment]
test this please

**Comment by milos1290** [comment]
test this please

**Comment by Enuviel** [comment]
test this please

**Comment by Enuviel** [comment]
test this please

**Comment by milos1290** [comment]
test this please

**Comment by milos1290** [comment]
test this please

**Comment by Enuviel** [comment]
test this please

**Comment by milos1290** [comment]
test this please

**Comment by milos1290** [comment]
test this please

**Comment by Enuviel** [comment]
test this please

**Comment by milos1290** [comment]
test this please

**Comment by milos1290** [comment]
test this please

**Pull request merged**
