### PR TITLE
feat(notifications): adds ability to customize which activity will be…

### PR DESCRIPTION
**Pull request by milos1290**
… launched

Provides a way to customize next steps when push notification is received.

### CODE REVIEW

**Comment by milos1290** [comment]
Sample usage, metadata can be attached to already used broadcast receivers.
AndroidManifest.xml
```
        <receiver android:name=".NotificationHandlerReceiver"/>
        <meta-data
            android:name="LP_NOTIFICATION"
            android:value="com.example.application.NotificationHandlerReceiver" />
```
Custom BroadcastReceiver
```
public class NotificationHandlerReceiver extends BroadcastReceiver {

  @Override
  public void onReceive(Context context, Intent intent) {
    String action = intent.getAction();
    if (LeanplumPushService.LEANPLUM_NOTIFICATION.equals(action)) {
      // Must be called to allow Leanplum SDK to track notification.
      Bundle data = LeanplumPushService.preHandlePushNotification(context, intent);

      // Notification data, containing action, message etc.
      Map<String, Object> notificationData = LeanplumPushService.parseNotificationBundle(data);

      Intent launchIntent = new Intent(context, MainActivity.class);
      launchIntent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_RESET_TASK_IF_NEEDED);
      context.startActivity(launchIntent);

      // Must be called to allow Leanplum SDK to track notification.
      LeanplumPushService.postHandlePushNotification(context, intent);
    }
  }
}
```

**Comment by benmarten** [comment]
Hm, according to the ticket the customer requested the possibility of being informed when a user clicks on a notification, similar to this in iOS: https://github.com/Leanplum/Leanplum-iOS-SDK/blob/62d728a6aa80263a1b1936eabd4773f43f41faf1/Leanplum-SDK/Classes/Leanplum.m#L1628

Looks like this serves a different purpose, does it?

**Comment by benmarten** [comment]
test this please

**Comment by benmarten** [comment]
^ FYI: this is the comment to trigger a build ;)

**Pull request merged**
